### PR TITLE
feat: add auto refresh to the url

### PR DESCRIPTION
**Pull request by esoubiran-aneo**
fix https://github.com/aneoconsulting/ArmoniK/issues/763

will retry after #326

### CODE REVIEW

**Comment by Barbapapazes** [comment]
Need to check with the datagrid navigate

**Review by Faust1-2was-Aneo — APPROVED** [review]

**Review by Faust1-2was-Aneo — APPROVED** [review]

**Comment by Faust1-2was-Aneo** [comment]
Hey @esoubiran-aneo, could you check the code before i left my review ? Thanks !

**Review by esoubiran-aneo — COMMENTED** [review]
ça me semble ok @Faust1-2was-Aneo 👍

**Review by Faust1-2was-Aneo — APPROVED** [review]

**Comment by Faust1-2was-Aneo** [comment]
Thanks, now we can merge it @esoubiran-aneo !

**Pull request merged**
