### PR TITLE
feat: add authorizations to tasks

### LINKED ISSUE #377: Handle `cancelTasks` authorization

### PR DESCRIPTION
**Pull request by esoubiran-aneo**
fix #377

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Faust1-2was-Aneo — APPROVED** [review]

**Comment by esoubiran-aneo** [comment]
<script>console.log('test')</script>

**Comment by esoubiran-aneo** [comment]
<script>aler("coucou")</script>

**Comment by esoubiran-aneo** [comment]
<script>console.log('test')</script>

**Comment by esoubiran-aneo** [comment]
<script>alert('coucou')</script>

**Pull request merged**
